### ISSUE TITLE
给大神打个招呼

### ISSUE THREAD

**Issue by keyganker** [zzboy/lucene#1]
请问大神后续的文章什么时候出啊？还有大神是基于哪个版本分析的啊？

**Comment by zzboy** [comment]
你好，你是怎么找到这个项目的？最近工作比较忙，一直没有更新，后面可能会把自己写的一个词典系统放上来，功能和lucene的fst差不多，但是性能好很多。

**Comment by keyganker** [comment]
你好~ 我是前段时间在学习lucene，想看一看源码，发现自己看起来比较吃力，就想找一下有没有前人的成果，然后就在github上搜到了你的系列文章~
另外也很想了解一下大神是如何学习开源项目的~
谢谢~

**Comment by zzboy** [comment]
大神真不敢当，你工作了吗？lucene是我刚开始工作的时候为了做一个功能调研开始看的，怎么看的话，每个人可能不同吧，我是先把大的框架捋了一遍，后来debug源码，看一个个的功能点。

**Comment by keyganker** [comment]
我已经工作了，目前主要是从事业务开发。私下自己也是有兴趣去学一些技术性的东西，之前就是因为有机会为同事分享索引相关的内容，然后整理资料的时候想拓展一下全文索引这一块儿。不过最终由于时间的关系分享的时候没能涉及到。
希望有机会可以多向你请教，也关注一下你提到的“词典系统”~
